### ISSUE TITLE
How to train a model?

### ISSUE THREAD

**Issue by PengboLiu** [yistLin/pytorch-dual-learning#1]
Could you give a short description about how to train a model and  how
 to translatie in readme？
thanks！

**Comment by yistLin** [comment]
README has been updated!
If you have any further question, feel free to discuss with us.

**Comment by PengboLiu** [comment]
Sorry, I still have 2 questions about you code..
1. I don't figure out how to train a LM in your code.
    I run the code in LM/main.py to get language and put the model in /data？
    What's more,I need to train bi-directional NMT, 2 NMT+2 LM, right?
2. my environment is py3.6+torch0.3，can I run your code?
thanks!!!!!!!!!!!!!

**Comment by yistLin** [comment]
1. Just pre-train 2 NMT + 2 LM, and put them wherever you want. Remember to specify the path to the models before you train dual-learning.
2. We also used py3.6 + pytorch 0.3
