### ISSUE TITLE
How to choose corpus of the training language model？

### ISSUE THREAD

**Issue by PengboLiu** [yistLin/pytorch-dual-learning#3]
I want to know if I want to train 2 language model (en&de), how to choose corpus?

**Comment by yistLin** [comment]
It's up to you.

But I suppose the language models may not function well when the distributions of vocabulary are varied in language model and translation model. So we trained both models with WMT'16 English-German.

**Comment by PengboLiu** [comment]
Ok! THANKS!
I want to train a  domain-adaptation MT model recently. I think I can use your code: train a model by parallel corpus and then use nonparallel in-domain-data  completing dual-game to improve trans quality. Do you think it can work?
Another question: I use 200w parallel corpus (en-de ) and Nvidia 1080Ti(12G), batchsize=32, but it says "cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58". I want to know what size of data  do you chose?

**Comment by yistLin** [comment]
1. This is also what we want to do, but we haven't try it yet.
2. We also met this problem but still have no idea how to solve it.
    ```
    cuda runtime error (2) : out of memory...
    ```
    And this not only occurred in dual-learning stage but also in NMT model pre-training stage. So we suppose the problem could be due to the inappropriate memory allocation in **pcyin/pytorch_nmt**.

**Comment by PengboLiu** [comment]
Maybe  we can use OpenNMT-py ...
