### ISSUE TITLE
when I try to use dual.py,an error occurs to me 【in beam(),list out of range when it runs about 1000+ steps】

### ISSUE THREAD

**Issue by yangkexin** [yistLin/pytorch-dual-learning#4]
when I try to use dual.py, an error occurs to me 【in beam(),list out of range when it runs about 1000+ steps】,and I have no idea how to deal with it... 
/home/workspace/pytorch-dual-learning-master/nmt/model.py in beam(self, src_sents, beam_size)
    419             for prev_hyp_id, word_id, new_hyp_score in zip(prev_hyp_ids.cpu().data, word_ids.cpu().data, top_new_hyp_scores.cpu().data):
    420 
--> 421                 tgt_dists = out_dists[prev_hyp_id] + [p_t_cpu[prev_hyp_id].unsqueeze(0)]
    422                 hyp_tgt_words = hypotheses[prev_hyp_id] + [word_id]
    423 

IndexError: list index out of range

**Comment by LDONT** [comment]
The same error occurred to me. Have you solved it?

**Comment by yangkexin** [comment]
yes, I haved lower the learning rate to 1e-5 and it seemed work, as someone said in other issues , this framework relies deeply on well pre-trained nmt model, so I used more bilingual sentenses than before to train them.
