### ISSUE TITLE
can not found some files

### ISSUE THREAD

**Issue by sjf156** [yistLin/pytorch-dual-learning#7]
i can not find these files  mention in trian-dual.sh ：model.wmt16-ende-small.best.bin
wmt16-de.pt wmt16-en.pt and others
and i also can not found in website in read.me 
please help me tell me the website to get them

**Comment by sjf156** [comment]
can you give me the nmt models?

**Comment by yistLin** [comment]
We're not going to provide the NMT models.

The files you mentioned are actually NMT models and language models. You have to prepare them by yourself.
